const CONFIG = {
    introTitle: 'Em à',
    introDesc: `Anh hỏi một câu nha',
    btnIntro: 'hihi',
    title: 'Các em có muốn làm ny của anh ko',
    desc: 'Nếu ko trả lơi mà thoát ra tức là muốn làm ny của anh r đó',
    btnYes: 'Vâng. Em muốn làm ny của anh',
    btnNo: 'Không. Anh mơ à',
    question:'Trên thế giới hơn 7 tỉ người mà sao em lại yêu anh ;))',
    btnReply: 'Gửi cho anh <3',
    reply: 'Em thích anh lâu rồi. Em muốn làm ny của anh ;)) ',
    mess: 'Anh biết mà 🥰. Yêu em nhiều nhiều 😘😘',
    messDesc: 'Tối nay 7h anh qua đón nhé công chúa.',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'https://m.me/huytrumsvzxc',
}
